### ISSUE TITLE
How to proceed from Selection of Points to their Manipulation?

### ISSUE THREAD

**Issue by sami10007** [tpoisot/digitize#11]
I do successfully everything until 
`data.points = digitize::DigitData(col = 'red')
`
I cannot proceed to the step `df = digitize::Calibrate(data.points, cal, 0.1, 0.4, 0.0, 0.6)` because the point data is not stored. The closure of the point selection window does not yield to the save. 

OS: Ubuntu 16.04 
Hardware: Dell PC i3 2013  
Installation of digitize: successful without warnings/errors   
Source: http://lukemiller.org/index.php/2011/06/digitizing-data-from-old-plots-using-digitize/   
Reproduction of the issue: http://unix.stackexchange.com/q/281674/16920

**Comment by ashander** [comment]
Your issue owes to your step 4 ("I close the Plot window because I cannot type in R prompt otherwise.") which prevents `locate` from working.

As [Luke Miller described](http://lukemiller.org/index.php/2011/06/digitizing-data-from-old-plots-using-digitize/) the way to get it working is 

> When you’re finished clicking points, you need to hit stop or right-click to stop the data point collection.

**Comment by sami10007** [comment]
Thank you! I do not see any "stop" button in the figure. The second-click worked.

**Comment by ashander** [comment]
No problem. I recently [improved the instructions](https://github.com/tpoisot/digitize/commit/db537a50720f02babb7e4458a285cd07ec513b98#diff-9fb8f312feeb8fa505f7c1f16a187daaR204) in our newer interface (just `mydata <- digitize("myfile.jpg")` and follow instructions on console. See [the readme](https://github.com/tpoisot/digitize/blob/master/README.md) for more
