### ISSUE TITLE
How to Do Selection of a Continuous Graph in Digitize?

### ISSUE THREAD

**Issue by sami10007** [tpoisot/digitize#14]
I am thinking what can be the uncertainty in doing it manually. How densely should you choose those points for a good result?

**Comment by ashander** [comment]
This seems like something to avoid if at all possible.

In most cases when a continuous curve is presented, there should be associated equations (or at least reproducible methods to get equations) for the curve.

The question you ask strikes me as a the inverse problem of [smoothing](https://en.wikipedia.org/wiki/Smoothing) which seeks to infer functions that capture important patterns in data. You're asking how to produce data along a curve that captures important aspects of an underlying curve. Perhaps there's a general literature on this question in mathematics or statistics.

**Comment by sami10007** [comment]
Yes, you are right. I think the inverse problem can be solved in Mathematica. Extra difficulty is with rasterized image. Howeverr, I am only interested in relative changes so not a problem for me, not to absolute units. I think this difficulty is the main reason why my thread of Mathematica got closed here http://mathematica.stackexchange.com/q/119336/9815 The points are distributed by the constant piecewise velocity. In the thread, you see the actual data that I use. 

It would be really great to get the formulation of the inverse problem such that I could better understand if the extraction is at all possible in Mathematica.
