### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by ashander** [tpoisot/digitize#9]
as mentioned in #6

- [x] package level doc
- [x] example in digitize
- [x] docs for compoenents

**Comment by sami10007** [comment]
I think the installation instructions can be improved and make more complete. Here my suggestion for installing digitize in Ubuntu 16.04: http://unix.stackexchange.com/q/281674/16920

**Comment by tpoisot** [comment]
@sami10007 none of the issues in the thread have to do with digitize.
